### ISSUE TITLE
am getting error

### ISSUE THREAD

**Issue by ramusesan** [thombrg/Homework#1]
am getting following error  when i  try to downloaded and run it 
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': The provided selector is empty.

**Comment by suryasaavn** [comment]
am getting following error when i try to downloaded and run it
Uncaught DOMException: Failed to execute 'querySelector' on 'Document': The provided selector is empty

**Comment by bevikram** [comment]
Failed to execute 'querySelector' on 'Document': The provided selector is empty
